name: warcraft_flutter_components_example
description: Example app for warcraft_flutter_components.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  warcraft_flutter_components:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
